# Model arguments
model_name_or_path: '/home/ubuntu/hieu.nn/Lang/alignment-handbook/data/stablelm-2-1_6b-spin-kto-0-full'
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  # HuggingFaceH4/ultrafeedback_binarized: 1.0
  '/home/ubuntu/hieu.nn/Lang/alignment-handbook/data/spin_data/stablelm-2-1_6b-spin-kto-0-full/ultrachat_200k_generated/1_5001': 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
loss_type: kto_pair
do_eval: false
evaluation_strategy: 'no'
eval_steps: 100
gradient_accumulation_steps: 10
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: stablelm-2-1_6b-spin-kto-1-full
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: data/stablelm-2-1_6b-spin-kto-1-full
per_device_train_batch_size: 1
per_device_eval_batch_size: 8
push_to_hub: true
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
precompute_ref_log_probs_path: /home/ubuntu/hieu.nn/Lang/alignment-handbook/data/stablelm-2-1_6b-spin-kto-1-full/ref_logprobs.pkl